config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }
  resources :users
  resources :camps
  resources :camp_applications do
    member do
      get 'camp/:camp_id/profile', to: 'camp_applications#profile', as: 'profile'
    end
    member do
      post '/auto_save', to: 'camp_applications#auto_save', as: 'auto_save'
    end
  end
  resources :privacy, only: [:index]

  devise_for :admins, controllers: { registrations: 'devise_admin/registrations', sessions: 'devise_admin/sessions' }
  namespace :admin_panel do
    get '/admin', to: 'home_page_admins#index', as: 'homepage'
    resources :admins
    resources :users
    resources :camp_applications
    resources :camp_locations do
      collection do
        get 'export_csv'
      end
    end
    resources :camps do
      member do
        patch :toggle_status
      end
    end
  end
  namespace :api do
    resources :camp_applications
  end

  namespace :api do
    namespace :v1 do
      resources :camps, only: %i[index]
    end
    namespace :v2 do
      post :auth, to: 'authentication#create'
      resources :camps, only: %i[index]
    end
  end

  root 'camps#index'

  match '*path', to: 'application#error_404', via: :all

end

app/models/camp_location.rb
class CampLocation < ApplicationRecord
  has_and_belongs_to_many :camps
  def self.search(search)
    if search
      where('name LIKE ? OR id LIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  def self.to_csv
    attributes = %w[name]
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |camp_location|
        csv << attributes.map { |attr| camp_location.send(attr) }
      end
    end
  end
end

app/controllers/admin_panel/admins_controller.rb
module AdminPanel
  class AdminsController < ApplicationController
    layout 'admin_layout'

    def show; end

    def edit; end

    def update
      current_admin.skip_password_validation = true
      if current_admin.update!(admin_params)
        bypass_sign_in(current_admin)
        redirect_to admin_panel_admin_path, notice: 'User was successfully updated.'
      else
        redirect_to admin_panel_homepage_path, notice: current_admin.errors
      end
    end

    private

    def admin_params
      params.require(:admin).permit(:first_name, :middle_name, :last_name, :email, :phone_number, :password, :password_confirmation, :image)
    end
  end
end

app/controllers/admin_panel/camp_applications_controller.rb
class AdminPanel::CampApplicationsController < ApplicationController
  layout 'admin_layout'
  before_action :set_camp_application, only: %i[show edit update destroy]

  def index
    @camp_applications = CampApplication.all
  end

  def show; end

  def edit
    current_user = @camp_application.user
    @camp_application.current_step = session[:application_step]
  end

  def update
    if session[:application_step] == 'personal_info'
      current_user = @camp_application.user
      current_user.skip_password_validation = true
      current_user.update!(user_params)
    else
      @camp_application.update!(camp_application_params)
    end
    @camp_application.current_step = session[:application_step]
    if params[:back_button]
      @camp_application.previous_step
    else
      @camp_application.next_step
    end
    session[:application_step] = @camp_application.current_step
    if params[:complete_button]
      render 'show'
    else
      redirect_to edit_admin_panel_camp_application_path(@camp_application)
    end
  end

  def destroy
    @camp_application.destroy
    redirect_to admin_panel_camp_applications_path, notice: 'Camp Application was Successfully destroyed.'
  end

  private

  def set_camp_application
    @camp_application = CampApplication.find(params[:id])
  end

  def camp_application_params
    params.require(:camp_application).permit %i[education camp_preferences technology_requirements social_media]
  end

  def user_params
    params.require(:user).permit %i[first_name middle_name last_name email phone_number date_of_birth gender]
  end
end

app/controllers/admin_panel/camp_locations_controller.rb
module AdminPanel
  class CampLocationsController < ApplicationController
    require 'csv'
    include Concerns::ColumnSortable
    before_action :set_location, only: %i[show edit update destroy]
    before_action :new_location, only: [:new]
    layout 'admin_layout'

    def index
      @camp_locations = CampLocation.search(params[:search]).order(sort_column => sort_direction).page(params[:page])
    end

    def new; end

    def edit; end

    def create
      @camp_location = CampLocation.new(camp_location_params)
      if @camp_location.save!
        redirect_to admin_panel_camp_location_path(@camp_location), alert: 'Camp location created successfully.'
      else
        redirect_to new_admin_panel_camp_location_path, alert: @camp_location.errors
      end
    end

    def show; end

    def destroy
      @camp_location.destroy!
      redirect_to admin_panel_camp_locations_path
    end

    def update
      if @camp_location.update!(camp_location_params)
        redirect_to admin_panel_camp_location_path(@camp_location), alert: 'Camp location updated successfully.'
      else
        render 'edit'
      end
    end

    def export_csv
      @camp_location = CampLocation.all
      respond_to do |format|
        format.html
        format.csv { send_data @camp_location.to_csv, filename: "camp_locations-#{Date.today}.csv" }
      end
    end

    def model_class
      CampLocation
    end

    private

    def new_location
      @camp_location = CampLocation.new
    end

    def set_location
      @camp_location = CampLocation.find(params[:id])
    end

    def camp_location_params
      params.require(:camp_location).permit(:name)
    end
  end
end

app/controllers/admin_panel/camps_controller.rb
module AdminPanel
  class CampsController < ApplicationController
    include Concerns::CampSortable
    layout 'admin_layout'
    before_action :authenticate_admin!
    before_action :set_camp, only: %i[show edit update destroy toggle_status]

    def index
      @camps = Camp.search(params[:search]).order(sort_camp_column => sort_camp_direction).page(params[:page])
      respond_to do |format|
        format.html
        format.csv do
          headers['Content-Disposition'] = 'attachment; filename="camps-list.csv"'
          headers['Content-Type'] ||= 'text/csv'
        end
      end
    end

    def show; end

    def new
      @camp = Camp.new
      @locations = CampLocation.all
    end

    def create
      @camp = Camp.new(camp_params)
      if @camp.save!
        redirect_to admin_panel_camp_path(@camp), notice: 'Camp was successfully created.'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @camp.update!(camp_params)
        redirect_to admin_panel_camps_path, notice: 'Camp was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @camp.destroy!
      redirect_to admin_panel_camps_path, notice: 'Camp was successfully destroyed.'
    end

    def toggle_status
      @camp.camp_status == 'active' ? (@camp.camp_status = 'inactive') : (@camp.camp_status = 'active')
      @camp_status = @camp.camp_status if @camp.save
    end

    def model_class_camp
      Camp
    end

    private

    def set_camp
      @camp = Camp.find(params[:id])
    end

    def new_camp_application
      @camp_application = CampApplication.where(user_id: current_user.id, camp_id: @camp.id).first
    end

    def camp_params
      params.require(:camp).permit(:camp_title, :camp_type, :camp_status, :applicant_registration_start_date, :applicant_registration_end_date, :applicant_registration_start_time, :applicant_registration_end_time, :parent_application_start_date, :parent_application_end_date, :parent_application_start_time, :parent_application_end_time, camp_location_ids: [])
    end
  end
end

app/controllers/admin_panel/home_page_admins_controller.rb
module AdminPanel
  class HomePageAdminsController < ApplicationController
    include Concerns::ColumnSortable

    before_action :authenticate_admin!
    helper_method :sort_column, :sort_direction
    skip_before_action :verify_authenticity_token
    layout 'admin_layout'

    def index
      @users = User.search(params[:search]).order(sort_column => sort_direction).page(params[:page])
      respond_to do |format|
        format.html
        format.csv do
          headers['Content-Disposition'] = 'attachment; filename="user-list.csv"'
          headers['Content-Type'] ||= 'text/csv'
        end
      end
    end

    def model_class
      User
    end
  end
end

app/controllers/admin_panel/users_controller.rb
module AdminPanel
  class UsersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_user, only: %i[show destroy edit update]
    layout 'admin_layout'

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.skip_password_validation = true
      @user.skip_confirmation!
      if @user.save!
        @user.invite!
        redirect_to admin_panel_homepage_path, notice: 'User was successfully Created.'
      else
        redirect_to admin_panel_homepage_path, notice: @user.errors
      end
    end

    def show; end

    def edit; end

    def update
      @user.skip_password_validation = true
      respond_to do |format|
        if @user.update!(user_params)
          format.html { redirect_to admin_panel_user_path, notice: 'User was successfully updated.' }
        else
          format.html { redirect_to admin_panel_homepage_path, notice: @user.errors }
        end
      end
    end

    def destroy
      if @user.destroy!
        respond_to do |format|
          format.html { redirect_to admin_panel_homepage_path, notice: 'User was successfully Destroyed.' }
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit %i[first_name middle_name last_name email country phone_number password password_confirmation image date_of_birth gender]
    end
  end
end

app/helpers/admin_panel/camp_applications_helper.rb
module AdminPanel::CampApplicationsHelper
end

app/helpers/camp_locations_helper.rb
module CampLocationsHelper
end

app/views/admin_panel/camp_locations/_camp_list.html.erb
<div class="table-responsive pa_20">
  <table id="mytable" class="table table-bordred table-striped">
    <thead>
      <th><%= sortable "name"%></th>
      <th>Actions</th>
    </thead>
    <tbody>
      <% @camp_locations.each do |camp_location| %>
        <tr>
          <td><%= camp_location.name %></td>
          <td>
            <%= link_to '<button class="btn buttons"><i class="material-icons table_icons">visibility</i></button>'.html_safe, admin_panel_camp_location_path(camp_location), title: 'Show Camp Location' %>
            <%= link_to '<button class="btn buttons"><i class="material-icons table_icons">create</i></button>'.html_safe, edit_admin_panel_camp_location_path(camp_location), title: 'Edit Camp Location' %>
            <%= link_to '<button class="btn buttons"><i class="material-icons table_icons">delete</i></button>'.html_safe,admin_panel_camp_location_path(camp_location), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete Camp Location'   %>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <%= paginate @camp_locations %>
<%= link_to 'Add New Location' ,new_admin_panel_camp_location_path,class: 'w_color btn btn-success'%>
<%= link_to 'Export CSV', export_csv_admin_panel_camp_locations_path(format: "csv"),  class: 'w_color btn btn-success' %>
</div>

app/views/admin_panel/camp_locations/_form.html.erb
<%= form_with model: [:admin_panel, @camp_location], local: true do |f| %>
  <div class="col-12">
    <%= render "shared/flash_message"%>
  </div>
  <div class="field col-12">
    <%= f.label :name, "Location Name*"%><br/>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'w_100' %>
  </div>
  <div class="row ml-1 mr-1">
  	<div class="col-6">
      <%= link_to 'Back', admin_panel_camp_locations_path, class: 'w_100 g_color any_links btn border border-success'%>
  	</div>
    <div class="actions col-6">
      <%= f.submit "Add Location", class: 'w_100 btn btn-success'  %>
    </div>
	</div>
<%end%>

app/views/admin_panel/camp_locations/edit.html.erb
<div class="container col-4 fp">
  <div class="main-content card card-block ">
    <div class="text-center p_20">
      <h2>Edit location</h2>
    </div>
    <hr/>
    <div class="card-body login-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin_panel/camp_locations/index.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div id="main"> 
  <div class="container pa_20"> 
    <div class="main-content card card-block">
      <div class="text-center pt-3">
        <h4>Locations for all camps</h4>
        <div class="row">
          <div class="col mr-4">
            <%= form_with method: :get, local: true do |f| %>
              <%= f.text_field :search,value: params[:search] %>
              <%= f.submit 'Search' %>
            <% end %> 
          </div>
        </div>
        <%= render 'admin_panel/camp_locations/camp_list', camp_locations: @camp_locations %>
      </div>
    </div>
  </div>
</div>

app/views/admin_panel/camp_locations/new.html.erb
<div class="container col-4 fp">
  <div class="main-content card card-block ">
    <div class="text-center p_20">
      <h2>Add new location</h2>
    </div>
    <hr/>
    <div class="card-body login-form">
       <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin_panel/camp_locations/show.html.erb
<div class="container col-4 fp">
  <div class="main-content card card-block ">
    <div class="text-center p_20">
      <h2>Location</h2>
    </div>
    <hr/>
    <div class="card-body login-form">
      <div class="w_100">
        <strong>Name:</strong>
        <%= @camp_location.name%>
      </div>
      <%= link_to 'Back' ,admin_panel_camp_locations_path,class: 'btn btn-success d-flex justify-content-center'%>
    </div>
  </div>
</div>