config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }
  resources :users
  resources :camps
  resources :camp_applications do
    member do
      get 'camp/:camp_id/profile', to: 'camp_applications#profile', as: 'profile'
    end
    member do
      post '/auto_save', to: 'camp_applications#auto_save', as: 'auto_save'
    end
  end
  resources :privacy, only: [:index]

  devise_for :admins, controllers: { registrations: 'devise_admin/registrations', sessions: 'devise_admin/sessions' }
  namespace :admin_panel do
    get '/admin', to: 'home_page_admins#index', as: 'homepage'
    resources :admins
    resources :users
    resources :camp_applications
    resources :camp_locations do
      collection do
        get 'export_csv'
      end
    end
    resources :camps do
      member do
        patch :toggle_status
      end
    end
  end
  namespace :api do
    resources :camp_applications
  end

  namespace :api do
    namespace :v1 do
      resources :camps, only: %i[index]
    end
    namespace :v2 do
      post :auth, to: 'authentication#create'
      resources :camps, only: %i[index]
    end
  end

  root 'camps#index'

  match '*path', to: 'application#error_404', via: :all

end

app/controllers/admin_panel/admins_controller.rb
module AdminPanel
  class AdminsController < ApplicationController
    layout 'admin_layout'

    def show; end

    def edit; end

    def update
      current_admin.skip_password_validation = true
      if current_admin.update!(admin_params)
        bypass_sign_in(current_admin)
        redirect_to admin_panel_admin_path, notice: 'User was successfully updated.'
      else
        redirect_to admin_panel_homepage_path, notice: current_admin.errors
      end
    end

    private

    def admin_params
      params.require(:admin).permit(:first_name, :middle_name, :last_name, :email, :phone_number, :password, :password_confirmation, :image)
    end
  end
end

app/controllers/admin_panel/camp_applications_controller.rb
class AdminPanel::CampApplicationsController < ApplicationController
  layout 'admin_layout'
  before_action :set_camp_application, only: %i[show edit update destroy]

  def index
    @camp_applications = CampApplication.all
  end

  def show; end

  def edit
    current_user = @camp_application.user
    @camp_application.current_step = session[:application_step]
  end

  def update
    if session[:application_step] == 'personal_info'
      current_user = @camp_application.user
      current_user.skip_password_validation = true
      current_user.update!(user_params)
    else
      @camp_application.update!(camp_application_params)
    end
    @camp_application.current_step = session[:application_step]
    if params[:back_button]
      @camp_application.previous_step
    else
      @camp_application.next_step
    end
    session[:application_step] = @camp_application.current_step
    if params[:complete_button]
      render 'show'
    else
      redirect_to edit_admin_panel_camp_application_path(@camp_application)
    end
  end

  def destroy
    @camp_application.destroy
    redirect_to admin_panel_camp_applications_path, notice: 'Camp Application was Successfully destroyed.'
  end

  private

  def set_camp_application
    @camp_application = CampApplication.find(params[:id])
  end

  def camp_application_params
    params.require(:camp_application).permit %i[education camp_preferences technology_requirements social_media]
  end

  def user_params
    params.require(:user).permit %i[first_name middle_name last_name email phone_number date_of_birth gender]
  end
end

app/controllers/admin_panel/camp_locations_controller.rb
module AdminPanel
  class CampLocationsController < ApplicationController
    require 'csv'
    include Concerns::ColumnSortable
    before_action :set_location, only: %i[show edit update destroy]
    before_action :new_location, only: [:new]
    layout 'admin_layout'

    def index
      @camp_locations = CampLocation.search(params[:search]).order(sort_column => sort_direction).page(params[:page])
    end

    def new; end

    def edit; end

    def create
      @camp_location = CampLocation.new(camp_location_params)
      if @camp_location.save!
        redirect_to admin_panel_camp_location_path(@camp_location), alert: 'Camp location created successfully.'
      else
        redirect_to new_admin_panel_camp_location_path, alert: @camp_location.errors
      end
    end

    def show; end

    def destroy
      @camp_location.destroy!
      redirect_to admin_panel_camp_locations_path
    end

    def update
      if @camp_location.update!(camp_location_params)
        redirect_to admin_panel_camp_location_path(@camp_location), alert: 'Camp location updated successfully.'
      else
        render 'edit'
      end
    end

    def export_csv
      @camp_location = CampLocation.all
      respond_to do |format|
        format.html
        format.csv { send_data @camp_location.to_csv, filename: "camp_locations-#{Date.today}.csv" }
      end
    end

    def model_class
      CampLocation
    end

    private

    def new_location
      @camp_location = CampLocation.new
    end

    def set_location
      @camp_location = CampLocation.find(params[:id])
    end

    def camp_location_params
      params.require(:camp_location).permit(:name)
    end
  end
end

app/controllers/admin_panel/camps_controller.rb
module AdminPanel
  class CampsController < ApplicationController
    include Concerns::CampSortable
    layout 'admin_layout'
    before_action :authenticate_admin!
    before_action :set_camp, only: %i[show edit update destroy toggle_status]

    def index
      @camps = Camp.search(params[:search]).order(sort_camp_column => sort_camp_direction).page(params[:page])
      respond_to do |format|
        format.html
        format.csv do
          headers['Content-Disposition'] = 'attachment; filename="camps-list.csv"'
          headers['Content-Type'] ||= 'text/csv'
        end
      end
    end

    def show; end

    def new
      @camp = Camp.new
      @locations = CampLocation.all
    end

    def create
      @camp = Camp.new(camp_params)
      if @camp.save!
        redirect_to admin_panel_camp_path(@camp), notice: 'Camp was successfully created.'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @camp.update!(camp_params)
        redirect_to admin_panel_camps_path, notice: 'Camp was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @camp.destroy!
      redirect_to admin_panel_camps_path, notice: 'Camp was successfully destroyed.'
    end

    def toggle_status
      @camp.camp_status == 'active' ? (@camp.camp_status = 'inactive') : (@camp.camp_status = 'active')
      @camp_status = @camp.camp_status if @camp.save
    end

    def model_class_camp
      Camp
    end

    private

    def set_camp
      @camp = Camp.find(params[:id])
    end

    def new_camp_application
      @camp_application = CampApplication.where(user_id: current_user.id, camp_id: @camp.id).first
    end

    def camp_params
      params.require(:camp).permit(:camp_title, :camp_type, :camp_status, :applicant_registration_start_date, :applicant_registration_end_date, :applicant_registration_start_time, :applicant_registration_end_time, :parent_application_start_date, :parent_application_end_date, :parent_application_start_time, :parent_application_end_time, camp_location_ids: [])
    end
  end
end

app/controllers/admin_panel/home_page_admins_controller.rb
module AdminPanel
  class HomePageAdminsController < ApplicationController
    include Concerns::ColumnSortable

    before_action :authenticate_admin!
    helper_method :sort_column, :sort_direction
    skip_before_action :verify_authenticity_token
    layout 'admin_layout'

    def index
      @users = User.search(params[:search]).order(sort_column => sort_direction).page(params[:page])
      respond_to do |format|
        format.html
        format.csv do
          headers['Content-Disposition'] = 'attachment; filename="user-list.csv"'
          headers['Content-Type'] ||= 'text/csv'
        end
      end
    end

    def model_class
      User
    end
  end
end

app/controllers/admin_panel/users_controller.rb
module AdminPanel
  class UsersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_user, only: %i[show destroy edit update]
    layout 'admin_layout'

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.skip_password_validation = true
      @user.skip_confirmation!
      if @user.save!
        @user.invite!
        redirect_to admin_panel_homepage_path, notice: 'User was successfully Created.'
      else
        redirect_to admin_panel_homepage_path, notice: @user.errors
      end
    end

    def show; end

    def edit; end

    def update
      @user.skip_password_validation = true
      respond_to do |format|
        if @user.update!(user_params)
          format.html { redirect_to admin_panel_user_path, notice: 'User was successfully updated.' }
        else
          format.html { redirect_to admin_panel_homepage_path, notice: @user.errors }
        end
      end
    end

    def destroy
      if @user.destroy!
        respond_to do |format|
          format.html { redirect_to admin_panel_homepage_path, notice: 'User was successfully Destroyed.' }
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit %i[first_name middle_name last_name email country phone_number password password_confirmation image date_of_birth gender]
    end
  end
end

app/helpers/admin_panel/camp_applications_helper.rb
module AdminPanel::CampApplicationsHelper
end

app/helpers/home_page_admin_helper.rb
module HomePageAdminHelper
end

app/helpers/home_page_admins_helper.rb
module HomePageAdminsHelper
end

app/views/admin_panel/home_page_admins/_list.html.erb
<div class="table-responsive p_20">
  <table id="mytable" class="table table-bordred table-striped">
    <thead>
      <th><input type="checkbox" /></th>
      <th><%= sortable "id"%></th>
      <th><%= sortable "username"%></th>
      <th><%= sortable "email"%></th>
      <th><%= sortable "country"%></th>
      <th><%= sortable "phone_number"%></th>
      <th>Actions</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><input type="checkbox" /></td>
          <td> <%= user.id %> </td>
          <td> <%= user.first_name %> </td>
          <td> <%= user.email %> </td>
          <td> <%= user.country_name %> </td>
          <td> <%= user.phone_number %> </td>
          <td>
            <%= link_to '<button class="btn buttons"><i class="material-icons table_icons">visibility</i></button>'.html_safe, admin_panel_user_path(user), title: 'Show User' %>
            <%= link_to '<button class="btn buttons"><i class="material-icons table_icons">create</i></button>'.html_safe, edit_admin_panel_user_path(user), title: 'Edit User' %>
            <%= link_to '<button class="btn buttons"><i class="material-icons table_icons">delete</i></button>'.html_safe,admin_panel_user_path(user), method: :delete, data: { confirm: 'Are you sure?' },  title: 'Delete User'   %>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @users %>
  </div>
    <%= link_to 'Add New User' ,new_admin_panel_user_path,class: 'w_color btn btn-success'%>
    &nbsp;&nbsp;&nbsp;
    <%= link_to 'Download CSV list', admin_panel_homepage_path(format: :csv), class: 'w_color btn btn-success'%>
</div>

app/views/admin_panel/home_page_admins/_show.html.erb
<div id="main">
  <div class="container mt-5 w-50">
    <div class="main-content card card-block">
      <div class="card-body text-center">
        <% if user.class.name == 'User' %> 
          <h2>User Profile</h2>
          <% else %>
          <h2>Admin Profile</h2>
        <%end%>
        <div id="container">
          <% if user.image.attached? %>
                <%= image_tag user.image, :class=> "img-circular"  %> 
          <% end %>
          <br>
          <br>
          <div id="left">Name</div>
          <div id="right"><%= user.first_name + ' '+ user.middle_name + ' '+ user.last_name %></div>
        </div>
        <br>
        <hr>
        <div id="container">
          <div id="left">Email</div>
          <div id="right"><%= user.email %></div>
        </div>
        <br>
        <hr>
         <div id="container">
          <div id="left">Phone Number</div>
          <div id="right"><%= user.phone_number %></div>
        </div>
        <br>
        <hr>
         <div id="container">
          <div id="left">Role</div>
          <% if user.class.name == 'User' %> 
          <div id="right"><%= User %></div>
          <% else %>
          <div id="right"><%= Admin %></div>
          <% end %>
        </div>
        <br>
        <% if user.class.name == 'User' %> 
        <hr>
         <div id="container">
          <div id="left">Country</div>
          <div id="right"><%= user.country%></div>
        </div>
        <br>
        <% end %>
        <hr>                 
      </div>
      <br>
      <% if user.class.name == 'Admin' %> 
      <div class="d-flex justify-content-center">
        <%= link_to 'Edit Admin', edit_admin_panel_admin_path(user) ,class: 'w_color btn btn-success'%>
      </div>
      <br>
      <% end %>
       <%= link_to "Back", admin_panel_homepage_path, class: 'btn btn-success w_color'%>
    </div>
  </div>
</div>

app/views/admin_panel/home_page_admins/index.csv.erb
<%- headers = ['First Name','Middle Name', 'Last Name' , 'Phone Number' , 'Email'] -%>
<%= CSV.generate_line headers %>
<%- @users.each do |user| -%>
<%= CSV.generate_line([user.first_name, user.middle_name, user.last_name, user.phone_number, user.email]) -%>
<%- end -%>

app/views/admin_panel/home_page_admins/index.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div id="main"> 
  <div class="container mt-5" > 
    <div class="main-content card card-block">
      <div class="text-center pt-4 pb-3">
        <h4>Users for Test Resident Camp</h4>
        <div class="row">        
          <div class="col">
            <%= form_with method: :get, local: true do |f| %>
              <%= f.text_field :search,value: params[:search] ,class:'mt-1' %>
              <%= f.submit 'Search' ,class:'btn btn-success btn-sm ml-2 '%>
            <% end %> 
          </div>
        </div>
        <%= render(partial: 'list', locals: { user: @users})%>
        </div>
      </div>
    </div>
  </div>
</div>