config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }
  resources :users
  resources :camps
  resources :camp_applications do
    member do
      get 'camp/:camp_id/profile', to: 'camp_applications#profile', as: 'profile'
    end
    member do
      post '/auto_save', to: 'camp_applications#auto_save', as: 'auto_save'
    end
  end
  resources :privacy, only: [:index]

  devise_for :admins, controllers: { registrations: 'devise_admin/registrations', sessions: 'devise_admin/sessions' }
  namespace :admin_panel do
    get '/admin', to: 'home_page_admins#index', as: 'homepage'
    resources :admins
    resources :users
    resources :camp_applications
    resources :camp_locations do
      collection do
        get 'export_csv'
      end
    end
    resources :camps do
      member do
        patch :toggle_status
      end
    end
  end
  namespace :api do
    resources :camp_applications
  end

  namespace :api do
    namespace :v1 do
      resources :camps, only: %i[index]
    end
    namespace :v2 do
      post :auth, to: 'authentication#create'
      resources :camps, only: %i[index]
    end
  end

  root 'camps#index'

  match '*path', to: 'application#error_404', via: :all

end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :camp_applications, dependent: :destroy
  has_many :users, through: :camp_applications
  has_and_belongs_to_many :camp_locations
  after_initialize :init

  validates :camp_type, inclusion: { in: %w[virtual real] }
  validates :camp_title, presence: true
  validates :applicant_registration_start_date, presence: true
  validates :applicant_registration_end_date, presence: true
  validates :applicant_registration_start_time, presence: true
  validates :applicant_registration_end_time, presence: true
  validates :parent_application_start_date, presence: true
  validates :parent_application_end_date, presence: true
  validates :parent_application_start_time, presence: true
  validates :parent_application_end_time, presence: true
  validate :validate_time_date

  

  def self.search(search)
    if search
      where('camp_title LIKE ? OR camp_type LIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  private

  def init
    self.camp_status ||= :inactive # will set the default camp status to Inactive
  end

  def validate_time_date
    unless applicant_registration_start_date.nil? && applicant_registration_end_date.nil? && parent_application_start_date.nil? && parent_application_end_date.nil?
      if applicant_registration_start_date > applicant_registration_end_date || parent_application_start_date > parent_application_end_date
        errors.add(:end_date, 'must be after the start date')
      end
    end
  end
end

app/controllers/admin_panel/camps_controller.rb
module AdminPanel
  class CampsController < ApplicationController
    include Concerns::CampSortable
    layout 'admin_layout'
    before_action :authenticate_admin!
    before_action :set_camp, only: %i[show edit update destroy toggle_status]

    def index
      @camps = Camp.search(params[:search]).order(sort_camp_column => sort_camp_direction).page(params[:page])
      respond_to do |format|
        format.html
        format.csv do
          headers['Content-Disposition'] = 'attachment; filename="camps-list.csv"'
          headers['Content-Type'] ||= 'text/csv'
        end
      end
    end

    def show; end

    def new
      @camp = Camp.new
      @locations = CampLocation.all
    end

    def create
      @camp = Camp.new(camp_params)
      if @camp.save!
        redirect_to admin_panel_camp_path(@camp), notice: 'Camp was successfully created.'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @camp.update!(camp_params)
        redirect_to admin_panel_camps_path, notice: 'Camp was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @camp.destroy!
      redirect_to admin_panel_camps_path, notice: 'Camp was successfully destroyed.'
    end

    def toggle_status
      @camp.camp_status == 'active' ? (@camp.camp_status = 'inactive') : (@camp.camp_status = 'active')
      @camp_status = @camp.camp_status if @camp.save
    end

    def model_class_camp
      Camp
    end

    private

    def set_camp
      @camp = Camp.find(params[:id])
    end

    def new_camp_application
      @camp_application = CampApplication.where(user_id: current_user.id, camp_id: @camp.id).first
    end

    def camp_params
      params.require(:camp).permit(:camp_title, :camp_type, :camp_status, :applicant_registration_start_date, :applicant_registration_end_date, :applicant_registration_start_time, :applicant_registration_end_time, :parent_application_start_date, :parent_application_end_date, :parent_application_start_time, :parent_application_end_time, camp_location_ids: [])
    end
  end
end

app/controllers/api/v1/camps_controller.rb
class Api::V1::CampsController < BaseController

	def index
      @camps = Camp.where(camp_status: 'Active')
      render json: @camps
    end

end

app/controllers/api/v2/camps_controller.rb
class Api::V2::CampsController < BaseController
	
	def index
      @camps = Camp.where(camp_status: 'Active')
      render json: @camps
    end

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :authenticate_user!

  def index
    @camps = Camp.where(camp_status: 'active')
    if @camps.count == 1
      @camp = @camps.first
      new_camp_application
      render template: 'camps/show.html.erb'
    else
      render 'index'
    end
  end

  def show
    @camp = Camp.find(params[:camp])
    new_camp_application
  end

  private

  def new_camp_application
    @camp_application = CampApplication.where(user_id: current_user.id, camp_id: @camp.id).first
    @camp_application = CampApplication.create!(user_id: current_user.id, camp_id: @camp.id) if @camp_application.nil?
  end
end

app/helpers/api/v1/camps_helper.rb
module Api::V1::CampsHelper
end

app/helpers/api/v2/camps_helper.rb
module Api::V2::CampsHelper
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/index.html.erb
<% if user_signed_in? %>
<div class="row">
  <p class="col-md-auto g_color">
    Hello, <%= current_user.username%>
  </p>
</div>
<%= link_to "Sign_Out", destroy_user_session_path, :method => 'delete', class: 'btn btn-success w_color'%>
<% end %>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div id="main"> 
  <div class="container col-3 p_20 fpe"> 
    <div class="main-content card card-block">
      <div class="ml-2" style="padding-top: 20px;">
        <h4 class="text-center">Select Camp</h4>
         <hr>
         <div class="table-responsive p_20">
          <% if @camps.count == 0 %>
            <p class="text-center">There are no active camps to show yet.</p>
          <% else %>
            <%= form_tag camp_path('?'), method: :get do %>
              <table id="mytable" class="table table-bordred table-striped">
                <p>Please Select the application you would like to access:</p>
                <tbody>
                  <% @camps.each do |camp| %>
                    <tr>
                      <td><%= radio_button_tag :camp, "#{camp.id}", false, required: 'true' %> </td>
                      <td><%= camp.camp_title %> </td> 
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="d-flex justify-content-center">
                <%= submit_tag :Continue , class:' su btn btn-success '%>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/camps/show.html.erb
<div class="container col-5 su" >
  <div class="main-content card card-block">
    <div class="ptlr_20">
      <%= link_to "Back", camps_path, class: 'btn btn-success w_color'%>
        <p>Welcome and thank you for applying to be a participant at <%= @camp.camp_title %>. CONNECT is an international programme for students ages 14 to 17 from around the world which takes place in partnership.

        The purpose of this application is for the CONNECT Placement Team to get to know you and learn about your interests, passions, and motivations for registering. Before registering, we encourage you to visit our website and learn more about our offerings and the registration process.

        This registration form is for both CONNECT camps that will take place during July 2022:
        CONNECT Cycle A: 1:30 AM GMT to 7:30 AM GMT
        CONNECT Cycle B: 11:30 AM GMT to 5:30 PM GMT

        If you have any questions during the application process, please feel free to email  at info@projectname.com.

        I AKNOWLEDGE AND AGREE THAT ANY INFORMATION PROVIDED IN THIS APPLICATION WILL BE COLLECTED AND PROCESSED IN ACCORDANCE WITH THE PRIVACY POLICY.
      </p>
    </div>
    <%= link_to "Continue", profile_camp_application_path(@camp_application,@camp), class: 'ml-4 btn btn-success w_color mr-4'%>
  </div>
</div>