config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }
  resources :users
  resources :camps
  resources :camp_applications do
    member do
      get 'camp/:camp_id/profile', to: 'camp_applications#profile', as: 'profile'
    end
    member do
      post '/auto_save', to: 'camp_applications#auto_save', as: 'auto_save'
    end
  end
  resources :privacy, only: [:index]

  devise_for :admins, controllers: { registrations: 'devise_admin/registrations', sessions: 'devise_admin/sessions' }
  namespace :admin_panel do
    get '/admin', to: 'home_page_admins#index', as: 'homepage'
    resources :admins
    resources :users
    resources :camp_applications
    resources :camp_locations do
      collection do
        get 'export_csv'
      end
    end
    resources :camps do
      member do
        patch :toggle_status
      end
    end
  end
  namespace :api do
    resources :camp_applications
  end

  namespace :api do
    namespace :v1 do
      resources :camps, only: %i[index]
    end
    namespace :v2 do
      post :auth, to: 'authentication#create'
      resources :camps, only: %i[index]
    end
  end

  root 'camps#index'

  match '*path', to: 'application#error_404', via: :all

end

app/models/user.rb
class User < ApplicationRecord
  has_many :camp_applications, dependent: :destroy
  has_many :camps, through: :camp_applications
  attr_accessor :skip_password_validation

  before_validation :add_username
  has_one_attached :image
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :password, password: true, unless: :skip_password_validation
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :country, presence: true
  #validates :gender, inclusion: { in: %w(man women other) }
  validates :phone_number, presence: true, format: { with: /(?:\+?\d{1,3}[- ]?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{2}[- ]?\d{2}/, message: 'only allows numbers' }, length: { in: 7..25 }
  def country_name
    country = self.country
    ISO3166::Country[country]
  end

  def self.search(search)
    if search
      where('username LIKE ? OR email LIKE ? OR id LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  def add_username
    self.username = [first_name, last_name].join
  end

  private

  def password_required?
    return false if skip_password_validation

    super
  end
end

app/controllers/admin_panel/users_controller.rb
module AdminPanel
  class UsersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_user, only: %i[show destroy edit update]
    layout 'admin_layout'

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.skip_password_validation = true
      @user.skip_confirmation!
      if @user.save!
        @user.invite!
        redirect_to admin_panel_homepage_path, notice: 'User was successfully Created.'
      else
        redirect_to admin_panel_homepage_path, notice: @user.errors
      end
    end

    def show; end

    def edit; end

    def update
      @user.skip_password_validation = true
      respond_to do |format|
        if @user.update!(user_params)
          format.html { redirect_to admin_panel_user_path, notice: 'User was successfully updated.' }
        else
          format.html { redirect_to admin_panel_homepage_path, notice: @user.errors }
        end
      end
    end

    def destroy
      if @user.destroy!
        respond_to do |format|
          format.html { redirect_to admin_panel_homepage_path, notice: 'User was successfully Destroyed.' }
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit %i[first_name middle_name last_name email country phone_number password password_confirmation image date_of_birth gender]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update]

  def show; end

  def edit; end

  def update
    @user.skip_password_validation = true
    respond_to do |format|
      if @user.update!(user_params)
        format.html { redirect_to user_path, notice: 'User was successfully updated.' }        
      else
        format.html { redirect_to homepage_path, notice: @user.errors }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit %i[first_name middle_name last_name email country phone_number password password_confirmation image date_of_birth gender]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<div id="main">
<div  class="container mt-4">
  <div class="main-content card card-block form-content">
    <div class="text-center pt-3" >
      <%= form_with model: @user, local: true do |f| %>
       <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>      
        <div class="image-upload" id="profile-pic" >
          <% if @user.image.attached? %>
              <%= image_tag @user.image, :class=> "img-circular"  %> 
          <% end %>
          <label for="file-input">
            <br>
            <i class="fas fa-camera fa-2x" onclick="uploadImage()"></i>
          </label>
           <%= f.file_field :image, id:"file-input" %>
        </div>
        <div class="row">
          <div class="field col-4">
            <%= f.label :first_name%><br />
            <%= f.text_field :first_name,autofocus: true, autocomplete: "first_name", class: 'w_100'%>
          </div>
          <div class="field col-4">
            <%= f.label :middle_name%><br />
            <%= f.text_field :middle_name,autofocus: true, autocomplete: "middle-name", class: 'w_100'%>
          </div>
          <div class="field col-4">
            <%= f.label :last_name%><br />
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last-name", class: 'w_100'%>
          </div>
        </div>
        <div class="row">
          <div class="field col-6">
            <%= f.label :email%><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'w_100'%>
          </div>
          <div class="field col-6">
            <%= f.label :country %><br />
            <%= f.country_select :country, [@user.country], {class: "btn border border-info"}, autofocus: true, autocomplete: "country"%>
          </div>
        </div>
          <div class="field col-4" style="margin: 0 auto">
            <%= f.label :phone_number %><br />
            <%= f.text_field :phone_number,autofocus: true, autocomplete: "phone-number", class:'quantity w_100'%>
          </div>
          <br>
          <div class="row">
          <div class="field col-6">
            <%= f.label :password %>         
            <%= f.password_field :password, class: 'w_100'%>
          </div>
          <div class="field col-6">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, class: 'w_100'%>
          </div>
        </div>                   
        <%= f.submit :Submit ,class:'btn btn-success'%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div id="main">
<div  class="container mt-4">
  <div class="main-content card card-block form-content">
    <div class="text-center pt-3" >
      <%= link_to "Back", homepage_path, class: 'btn btn-success w_color'%>
      <%= form_with model: @user, local: true do |f| %>
       <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>      
        <div class="image-upload" id="profile-pic" >
          <% if @user.image.attached? %>
              <%= image_tag @user.image, :class=> "img-circular"  %> 
          <% end %>
          <label for="file-input">
            <br>
            <i class="fas fa-camera fa-2x" onclick="uploadImage()"></i>
          </label>
           <%= f.file_field :image, id:"file-input" %>
        </div>
        <div class="row">
          <div class="field col-4">
            <%= f.label :first_name%><br />
            <%= f.text_field :first_name,autofocus: true, autocomplete: "first_name", class: 'w_100'%>
          </div>
          <div class="field col-4">
            <%= f.label :middle_name%><br />
            <%= f.text_field :middle_name,autofocus: true, autocomplete: "middle-name", class: 'w_100'%>
          </div>
          <div class="field col-4">
            <%= f.label :last_name%><br />
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last-name", class: 'w_100'%>
          </div>
        </div>
        <div class="row">
          <div class="field col-6">
            <%= f.label :email%><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'w_100'%>
          </div>
          <div class="field col-6">
            <%= f.label :country %><br />
            <%= f.country_select :country, [@user.country], {class: "btn border border-info"}, autofocus: true, autocomplete: "country"%>
          </div>
        </div>
          <div class="field col-4" style="margin: 0 auto">
            <%= f.label :phone_number %><br />
            <%= f.number_field :phone_number,autofocus: true, autocomplete: "phone-number", class:'quantity w_100'%>
          </div>
          <br>
          <div class="row">
          <div class="field col-6">
            <%= f.label :password %>         
            <%= f.password_field :password, class: 'w_100'%>
          </div>
          <div class="field col-6">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, class: 'w_100'%>
          </div>
        </div>                   
        <%= f.submit :Submit ,class:'btn btn-success'%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/personal_info.html.erb
<div id="main">
<div  class="container mt-4">
  <div class="main-content card card-block form-content">
    <div class="text-center pt-3" >
      <%= form_with model: @user,url: save_user_personal_info_path, local: true do |f| %>
       <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>     
        <h2> <%= @user.gender %> </h2>

        <div class="image-upload" id="profile-pic" >
          <% if @user.image.attached? %>
              <%= image_tag @user.image, :class=> "img-circular"  %> 
          <% end %>
          <label for="file-input">
            <br>
            <i class="fas fa-camera fa-2x" onclick="uploadImage()"></i>
          </label>
           <%= f.file_field :image, id:"file-input" %>
        </div>

        <div class="row">
          <div class="field col-4">
            <%= f.label :first_name%><br />
            <%= f.text_field :first_name,autofocus: true, autocomplete: "first_name", class: 'w_100'%>
          </div>
          <div class="field col-4">
            <%= f.label :middle_name%><br />
            <%= f.text_field :middle_name,autofocus: true, autocomplete: "middle-name", class: 'w_100'%>
          </div>
          <div class="field col-4">
            <%= f.label :last_name%><br />
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last-name", class: 'w_100'%>
          </div>
        </div>
        <div class="row">
          <div class="field col-6">
            <%= f.label :email%><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'w_100'%>
          </div>          
          <div class="field col-6">
            <%= f.label :phone_number %><br />
            <%= f.number_field :phone_number, autofocus: true, autocomplete: "phone-number", class:'quantity w_100'%>
          </div>           
        </div>
        <div class="row d-flex justify-content-center">
          <div class="field">
             <%= f.label :date_of_birth %><br />           
            <%= f.date_select :date_of_birth  %>
          </div>
        </div>
          <br>

        <div class="field">
          <%=f.label :gender %><br>
          <%= f.radio_button :gender, 'man'%>MAN
          <%= f.radio_button :gender, 'women'%>WOMEN 
          <%= f.radio_button :gender, 'other'%>OTHER
        </div>          
        <%= f.submit :Submit, class:'btn btn-succes', id:'submit' %>
        <%= link_to 'Skip', users_path,class: 'btn btn-success'%>
        <%= link_to 'Back', users_path,class: 'btn btn-success'%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="main">
  <div class="container mt-5 w-50">
    <div class="main-content card card-block">
      <div class="card-body text-center">
        <% if current_user.class.name == 'User' %> 
          <h2>User Profile</h2>
          <% else %>
          <h2>Admin Profile</h2>
        <%end%>
        <div id="container">
          <% if current_user.image.attached? %>
                <%= image_tag current_user.image, :class=> "img-circular"  %> 
          <% end %>
          <br>
          <br>
          <div id="left">Name</div>
          <div id="right"><%= current_user.first_name + ' '+ current_user.middle_name + ' '+ current_user.last_name %></div>
        </div>
        <br>
        <hr>
        <div id="container">
          <div id="left">Email</div>
          <div id="right"><%= current_user.email %></div>
        </div>
        <br>
        <hr>
         <div id="container">
          <div id="left">Phone Number</div>
          <div id="right"><%= current_user.phone_number %></div>
        </div>
        <br>
        <hr>
         <div id="container">
          <div id="left">Role</div>          
          <div id="right"><%= User %></div>          
        </div>
        <br>
        <% if current_user.class.name == 'User' %> 
        <hr>
         <div id="container">
          <div id="left">Country</div>
          <div id="right"><%= current_user.country%></div>
        </div>
        <br>
        <% end %>
        <hr>                 
      </div>
      <br>
      <div class="d-flex justify-content-center">
        <%= link_to 'Edit User', edit_admin_panel_admin_path(current_user) ,class: 'w_color btn btn-success'%>
      </div>
      <br>      
       <%= link_to "Back", admin_panel_homepage_path, class: 'btn btn-success w_color'%>
    </div>
  </div>
</div>